name: fspn
channels:
  - ankurankan
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - ca-certificates=2020.6.20=hecda079_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.2=he06d7ca_0
  - glib=2.65.0=h3eb4bd4_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=hf484d3e_1000
  - importlib-metadata=1.6.1=py37hc8dfbb8_0
  - importlib_metadata=1.6.1=0
  - intel-openmp=2020.1=217
  - ipykernel=5.3.0=py37h43977f1_0
  - ipython=7.15.0=py37hc8dfbb8_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.0=py37hc8dfbb8_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - krb5=1.16.4=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hed695b0_1
  - libpq=11.2=h20c2e04_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=he19cac6_1
  - markupsafe=1.1.1=py37h8f50634_1
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mistune=0.8.4=py37h8f50634_1001
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.6=py_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - notebook=6.0.3=py37hc8dfbb8_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - openssl=1.1.1g=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pgmpy=0.1.10=py37_0
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pip=20.0.2=py37_3
  - pomegranate=0.11.1=py37ha516724_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_0
  - psycopg2=2.8.4=py37h1ba5d50_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pygments=2.6.1=py_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pyrsistent=0.16.0=py37h8f50634_0
  - python=3.7.7=h191fe78_0_cpython
  - python_abi=3.7=1_cp37m
  - pytorch=1.3.1=cuda100py37h53c1284_0
  - pyzmq=19.0.1=py37hac76be4_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - send2trash=1.5.0=py_0
  - setuptools=47.1.1=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - sqlite=3.31.1=h62c20be_1
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py37h8f50634_1
  - traitlets=4.3.3=py37hc8dfbb8_1
  - wcwidth=0.2.4=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py37_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=h96e3832_1
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - arff==0.9
    - asn1crypto==0.24.0
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - bloom-filter==1.3
    - certifi==2019.3.9
    - cffi==1.12.3
    - chardet==3.0.4
    - cloudpickle==1.2.1
    - colorama==0.4.1
    - cryptography==2.9.2
    - dask==1.2.0
    - decorator==4.4.0
    - ete3==3.1.1
    - idna==2.6
    - joblib==0.13.2
    - keyring==10.6.0
    - keyrings-alt==3.0
    - kiwisolver==1.1.0
    - lark-parser==0.7.1
    - locket==0.2.0
    - matplotlib==3.0.3
    - mock==3.0.4
    - more-itertools==7.0.0
    - mpmath==1.1.0
    - networkx==2.3
    - numexpr==2.6.9
    - numpy==1.16.3
    - pandas==0.23.4
    - partd==1.0.0
    - patsy==0.5.1
    - pluggy==0.9.0
    - py==1.8.0
    - py4j==0.10.8.1
    - pybind11==2.3.0
    - pycparser==2.19
    - pycrypto==2.6.1
    - pydot==1.4.1
    - pyparsing==2.4.0
    - pyqt5==5.12.1
    - pyqt5-sip==4.19.15
    - pytest==4.4.1
    - python-dateutil==2.7.5
    - pytz==2018.7
    - pyverdict==0.1.3.2
    - pyxdg==0.25
    - pyyaml==3.12
    - requests==2.18.4
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - secretstorage==2.3.1
    - six==1.12.0
    - sklearn==0.0
    - spflow==0.0.34
    - sqlalchemy==1.3.11
    - sqlparse==0.3.0
    - statsmodels==0.9.0
    - sympy==1.4
    - tables==3.5.1
    - toolz==0.9.0
    - tqdm==4.31.1
    - urllib3==1.22
    - var-dump==1.2
    - wincertstore==0.2
prefix: /home/ziniu.wzn/anaconda3/envs/deepdb

